// sdk_freeze_test.go pins the public surface of the SDK at v1.
//
// Any breakage of these tests means you're about to ship a backwards-
// incompatible SDK change. Two paths forward:
//
//  1. Roll back — keep the v1 contract.
//  2. Open a v2 module under packages/sdk-go/v2/ and leave v1 untouched.
//
// Do NOT edit this file to make the test pass. The whole point is that
// updating the freeze requires conscious sign-off in a separate PR.

package sdk

import (
	"reflect"
	"sort"
	"strings"
	"testing"
)

// frozenManifestFields lists every (field name, JSON tag, Go type) in Manifest
// that the v1 contract pins. Tags use the FULL `json:"..."` value as
// written in source.
var frozenManifestFields = []frozenField{
	{"ID", `json:"id"`, "string"},
	{"Name", `json:"name"`, "string"},
	{"Version", `json:"version"`, "string"},
	{"Category", `json:"category"`, "sdk.Category"},
	{"Mode", `json:"mode"`, "sdk.Mode"},
	{"Description", `json:"description"`, "string"},
	{"ConfigSchema", `json:"configSchema"`, "json.RawMessage"},
}

var frozenRecordFields = []frozenField{
	{"Timestamp", `json:"timestamp"`, "time.Time"},
	{"ConnectorID", `json:"connectorId"`, "string"},
	{"SourceID", `json:"sourceId,omitempty"`, "string"},
	{"Location", `json:"location,omitempty"`, "*sdk.GeoPoint"},
	{"Tags", `json:"tags,omitempty"`, "map[string]string"},
	{"Payload", `json:"payload"`, "json.RawMessage"},
}

var frozenGeoPointFields = []frozenField{
	{"Lat", `json:"lat"`, "float64"},
	{"Lng", `json:"lng"`, "float64"},
	{"Altitude", `json:"altitude,omitempty"`, "*float64"},
}

// frozenInterfaceMethods is method name → method signature (as Method.Type.String()
// reports it, with the receiver dropped). The signatures are exactly what
// reflect.Type.Method(i).Type.String() returns.
var frozenConnectorMethods = map[string]string{
	"Manifest": "func() sdk.Manifest",
	"Validate": "func(json.RawMessage) error",
	"Run":      "func(context.Context, sdk.Context, json.RawMessage) error",
}

var frozenContextMethods = map[string]string{
	"Publish":         "func(context.Context, sdk.Record) error",
	"Logger":          "func() sdk.Logger",
	"Secret":          "func(string) string",
	"Checkpoint":      "func(context.Context, string, string) error",
	"LoadCheckpoint":  "func(context.Context, string) (string, error)",
}

var frozenLoggerMethods = map[string]string{
	"Debug": "func(string, ...interface {})",
	"Info":  "func(string, ...interface {})",
	"Warn":  "func(string, ...interface {})",
	"Error": "func(string, ...interface {})",
}

var frozenPushHandlerMethods = map[string]string{
	"BuildPushHandler": "func(sdk.Context, json.RawMessage) (http.Handler, error)",
}

var frozenModeValues = []Mode{ModePull, ModePush, ModeStream}

var frozenCategoryValues = []Category{
	CategoryGeophysical, CategoryWeather, CategoryAirQuality,
	CategoryHydrology, CategoryWildfire, CategoryStructural,
	CategoryIoT, CategoryIndustrial, CategoryCustom,
}

type frozenField struct {
	Name    string
	JSONTag string
	GoType  string
}

func TestFreeze_ManifestFields(t *testing.T) {
	assertFrozenStruct(t, "Manifest", reflect.TypeOf(Manifest{}), frozenManifestFields)
}

func TestFreeze_RecordFields(t *testing.T) {
	assertFrozenStruct(t, "Record", reflect.TypeOf(Record{}), frozenRecordFields)
}

func TestFreeze_GeoPointFields(t *testing.T) {
	assertFrozenStruct(t, "GeoPoint", reflect.TypeOf(GeoPoint{}), frozenGeoPointFields)
}

func TestFreeze_ConnectorInterface(t *testing.T) {
	assertFrozenInterface(t, "Connector",
		reflect.TypeOf((*Connector)(nil)).Elem(), frozenConnectorMethods)
}

func TestFreeze_ContextInterface(t *testing.T) {
	assertFrozenInterface(t, "Context",
		reflect.TypeOf((*Context)(nil)).Elem(), frozenContextMethods)
}

func TestFreeze_LoggerInterface(t *testing.T) {
	assertFrozenInterface(t, "Logger",
		reflect.TypeOf((*Logger)(nil)).Elem(), frozenLoggerMethods)
}

func TestFreeze_PushHandlerInterface(t *testing.T) {
	assertFrozenInterface(t, "PushHandler",
		reflect.TypeOf((*PushHandler)(nil)).Elem(), frozenPushHandlerMethods)
}

func TestFreeze_ModeValues(t *testing.T) {
	want := []string{"pull", "push", "stream"}
	got := []string{}
	for _, m := range frozenModeValues {
		got = append(got, string(m))
	}
	sort.Strings(want)
	sort.Strings(got)
	if !reflect.DeepEqual(want, got) {
		t.Fatalf("Mode values changed: got %v, want %v", got, want)
	}
}

func TestFreeze_CategoryValues(t *testing.T) {
	want := map[string]bool{
		"geophysical": true, "weather": true, "air_quality": true,
		"hydrology": true, "wildfire": true, "structural": true,
		"iot": true, "industrial": true, "custom": true,
	}
	for _, c := range frozenCategoryValues {
		if !want[string(c)] {
			t.Errorf("unexpected category %q (was %q removed or renamed?)", c, c)
		}
		delete(want, string(c))
	}
	for k := range want {
		t.Errorf("missing category %q from frozen set", k)
	}
}

func TestFreeze_SDKVersionIsV1(t *testing.T) {
	if !strings.HasPrefix(SDKVersion, "1.") {
		t.Fatalf("SDKVersion = %q; the SDK is FROZEN at v1. A new major requires a new module path (sdk-go/v2/).", SDKVersion)
	}
}

// assertFrozenStruct verifies exact match between t's exported fields and
// the supplied list (order matters for stable JSON marshaling).
func assertFrozenStruct(t *testing.T, name string, ty reflect.Type, want []frozenField) {
	t.Helper()
	if ty.Kind() != reflect.Struct {
		t.Fatalf("%s is not a struct", name)
	}
	if ty.NumField() != len(want) {
		t.Fatalf("%s: got %d fields, want %d. The struct grew or shrank — this is a freeze violation.", name, ty.NumField(), len(want))
	}
	for i, w := range want {
		got := ty.Field(i)
		if got.Name != w.Name {
			t.Errorf("%s.field[%d]: got name %q, want %q", name, i, got.Name, w.Name)
		}
		tag := string(got.Tag)
		if tag != w.JSONTag {
			t.Errorf("%s.%s: got tag %q, want %q (JSON contract change is BREAKING)", name, got.Name, tag, w.JSONTag)
		}
		if normalize(got.Type.String()) != w.GoType {
			t.Errorf("%s.%s: got type %q, want %q", name, got.Name, got.Type.String(), w.GoType)
		}
	}
}

// assertFrozenInterface verifies the interface declares exactly the listed
// methods with the listed signatures.
func assertFrozenInterface(t *testing.T, name string, ty reflect.Type, want map[string]string) {
	t.Helper()
	got := map[string]string{}
	for i := 0; i < ty.NumMethod(); i++ {
		m := ty.Method(i)
		got[m.Name] = m.Type.String()
	}
	if len(got) != len(want) {
		t.Fatalf("%s interface method count = %d, want %d. Got: %v", name, len(got), len(want), got)
	}
	for n, wantSig := range want {
		gotSig, ok := got[n]
		if !ok {
			t.Errorf("%s: missing method %q (removal is a freeze violation)", name, n)
			continue
		}
		if gotSig != wantSig {
			t.Errorf("%s.%s: got signature %q, want %q", name, n, gotSig, wantSig)
		}
	}
}

// normalize strips spaces that show up in interface{}/any rendering across
// Go versions, and collapses time.Time-style prefixes that are
// version-stable but visually noisy.
func normalize(s string) string { return strings.ReplaceAll(s, " ", "") }
