{{- if include "sunny.hasSecrets" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sunny.fullname" . }}
  labels: {{- include "sunny.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.auth.passwordHash }}
  SUNNY_PASSWORD_HASH: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.sessionKey }}
  SUNNY_SESSION_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.apiTokens }}
  SUNNY_API_TOKENS: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.issuer }}
  SUNNY_OIDC_ISSUER: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.clientId }}
  SUNNY_OIDC_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.clientSecret }}
  SUNNY_OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.redirectUrl }}
  SUNNY_OIDC_REDIRECT_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.scopes }}
  SUNNY_OIDC_SCOPES: {{ . | quote }}
  {{- end }}
  {{- with .Values.alerts.webhookUrl }}
  SUNNY_ALERTS_WEBHOOK_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.alerts.slackUrl }}
  SUNNY_ALERTS_SLACK_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.nasaFirmsKey }}
  SUNNY_SECRET_NASA_FIRMS_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.openaqApiKey }}
  SUNNY_SECRET_OPENAQ_API_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
