{{- if or .Values.auth.passwordHash .Values.auth.sessionKey .Values.secrets.nasaFirmsKey .Values.secrets.openaqApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sunny.fullname" . }}
  labels: {{- include "sunny.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.passwordHash }}
  SUNNY_PASSWORD_HASH: {{ .Values.auth.passwordHash | quote }}
  {{- end }}
  {{- if .Values.auth.sessionKey }}
  SUNNY_SESSION_KEY: {{ .Values.auth.sessionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.nasaFirmsKey }}
  SUNNY_SECRET_NASA_FIRMS_KEY: {{ .Values.secrets.nasaFirmsKey | quote }}
  {{- end }}
  {{- if .Values.secrets.openaqApiKey }}
  SUNNY_SECRET_OPENAQ_API_KEY: {{ .Values.secrets.openaqApiKey | quote }}
  {{- end }}
{{- end }}
